---
 - name: restart routing
   service: name=routing state=restarted
   listen: "restart routing"
   ignore_errors: yes

 - name: start bird
   service: name=bird state=started
   listen: "start bird"
   ignore_errors: yes

 - name: reload bird
   service: name=bird state=reloaded
   listen: "reload bird"
   ignore_errors: yes
