---
 - name: install haproxy
   pkgng: name=haproxy state=present

 - name: create haproxy account
   user:
     name: haproxy

 - name: enable haproxy
   service: name=haproxy enabled=yes

 - name: configure haproxy
   template: src=haproxy.conf dest=/usr/local/etc/haproxy.conf
   notify: restart haproxy

 - name: configure haproxy primary CARP address
   lineinfile:
    path: /etc/rc.conf
    regexp: '^ifconfig_{{ carp_interface }}_alias0='
    line: 'ifconfig_{{ carp_interface }}_alias0="inet vhid {{ carp_vhid }} pass testpass alias {{ carp_address }}/32"'
   when: carp_role == "primary"
   notify: restart network

 - name: configure haproxy secondary CARP address
   lineinfile:
    path: /etc/rc.conf
    regexp: '^ifconfig_{{ carp_interface }}_alias0='
    line: 'ifconfig_{{ carp_interface }}_alias0="inet vhid {{ carp_vhid }} advskew 100 pass testpass alias {{ carp_address }}/32"'
   when: carp_role == "secondary"
   notify: restart network
