---
 - name: install haproxy
   pkgng: name=haproxy state=present

 - name: configure haproxy primary CARP address
   lineinfile:
    path: /etc/rc.conf
    regexp: '^ifconfig_{{ carp_interface }}_alias0='
    line: 'ifconfig_{{ carp_interface }}_alias0="inet vhid {{ carp_vhid }} pass testpass alias {{ carp_address }}/32"'
   when: carp_role == "primary"
   notify: restart network

 - name: configure haproxy secondary CARP address
   lineinfile:
    path: /etc/rc.conf
    regexp: '^ifconfig_{{ carp_interface }}_alias0='
    line: 'ifconfig_{{ carp_interface }}_alias0="inet vhid {{ carp_vhid }} advskew 100 pass testpass alias {{ carp_address }}/32"'
   when: carp_role == "secondary"
   notify: restart network
