---
 - hosts: '{{ target }}'
   tasks:
   - name: clean pkg cache
     raw: env PAGER=cat pkg clean -ay

   - name: update pkg meta
     raw: env PAGER=cat pkg update

   - name: remove unused pkgs
     raw: env PAGER=cat pkg autoremove -y
     register: autoremove
     changed_when: "'Deinstallation has been requested' in autoremove.stdout"
