---
 - hosts: freebsd_common
   roles:
    - freebsd_common

 - hosts: bhyve_guests
   roles:
    - bhyve_guests

 - hosts: metrics-runner
   roles:
    - metrics-runner

 - hosts: 192.168.1.60
   roles:
    - nginx_proxy

 - hosts: 79c5ba-fw
   roles:
    - vlan_fw_nat_dhcp
