---
 - hosts: freebsd_common
   roles:
    - freebsd_common

 - hosts: centos_common
   roles:
    - centos_common

 - hosts: bhyve_guests
   roles:
    - bhyve_guests

 - hosts: kickstart
   roles:
    - nginx

 - hosts: jailwerld
   roles:
    - vimage_host

 - hosts: plex
   roles:
    - plex
