---
 - hosts: freebsd_common
   roles:
    - freebsd_common

 - hosts: 2e52-minio, 5868-minio, 98fb-minio, a6d3-minio
   roles:
    - minio

 - hosts: e38f-vmm
   roles:
    - vm_bhyve

 - hosts: 1728-jenkins-master
   roles:
    - jenkins_master

 - hosts: eee8-jenkins-agent, ca72-jenkins-agent, 1d0b-jenkins-agent, ff1c-jenkins-agent
   roles:
    - jenkins_agent

 - hosts: 16df-src-haproxy, feee-src-haproxy, 2b58-elasticsearch-haproxy, 43d9-elasticsearch-haproxy, 3643-kibana-haproxy, 324e-kibana-haproxy, d9ed-minio-haproxy, 4588-minio-haproxy
   roles:
    - haproxy

 - hosts: 0ace-elasticsearch, 4d28-elasticsearch, 6289-elasticsearch
   roles:
    - elasticsearch

 - hosts: 6745-src, ef94-src, ff0b-src
   roles:
    - src 

 - hosts: 1d21-api, 3159-api, 7dd0-api, d2a1-api
   roles:
    - dm_router
    - etcd
    - minio

 - hosts: 09f4-vmm, 2ab1-vmm, 2ed4-vmm, 4473-vmm, 5e09-vmm, f7e3-vmm
   roles:
    - dm_provider

 - hosts: 50df-logger-node, 5328-logger-node, 6eb8-logger-node, c629-logger-node, e124-logger-node
   roles:
    - logger_node
