---
 - hosts: freebsd_common
   roles:
    - freebsd_common

 - hosts: 1d21-api, 3159-api, 7dd0-api, d2a1-api
   roles:
    - minio

 - hosts: 1d21-api, 3159-api, 7dd0-api, d2a1-api
   roles:
    - dm_router

 - hosts: 09f4-vmm, 2ab1-vmm, 2ed4-vmm, 4473-vmm, 5e09-vmm, f7e3-vmm
   roles:
    - dm_provider
