---
 - hosts: freebsd_common
   roles:
    - freebsd_common

 - hosts: centos_common
   roles:
    - centos_common

 - hosts: bhyve_guests
   roles:
    - bhyve_guests

 - hosts: rc1
   roles:
    - desktop

 - hosts: 192.168.1.67
   roles:
    - metrics-runner

 - hosts: kickstart
   roles:
    - nginx

 - hosts: 79c5ba-fw
   roles:
    - to-vlan_fw_nat_dhcp

 - hosts: jailwerld
   roles:
    - vimage_host

 - hosts: plex
   roles:
    - plex

 - hosts: 0a5647
   roles:
    - centos_mariadb
