---
 - hosts: '{{ target }}'
   tasks:
   - name: freebsd-update fetch
     raw: env PAGER=cat freebsd-update fetch

   - name: freebsd-update install
     raw: env PAGER=cat freebsd-update install
     ignore_errors: true

   - name: reboot
     shell: shutdown -r +1sec
     ignore_errors: true
