---

 - name: disable swap
   lineinfile:
    path: /etc/fstab
    state: absent
    regexp: 'swap'
   register: trigger_reboot

 - name: configure apk
   lineinfile:
    path: /etc/apk/repositories
    line: 'http://mirror.leaseweb.com/alpine/edge/testing'

 - name: install packages
   apk: name=kubernetes,docker,bird state=present

 - name: enable docker
   service:
    name: docker
    enabled: yes
    state: started

 - name: place kubeconfig
   template:
    src: kubeconfig
    dest: /root/kubeconfig
    owner: root
    group: wheel
    mode: 0600
   notify: restart kubelet

 - name: place kubleconf
   template:
    src: kubelet
    dest: /etc/init.d/kubelet
    owner: root
    group: wheel
    mode: 0755

 - name: place docker conf
   template:
    src: docker
    dest: /etc/conf.d/docker
    owner: root
    group: wheel
    mode: 0644

 - name: enable and start kubelet
   service:
    name: kubelet
    enabled: yes
    state: started

 - name: Reboot immediately if there was a change.
   shell: "sleep 5 && reboot"
   async: 1
   poll: 0
   when: trigger_reboot is changed

 - name: Wait for the reboot to complete if there was a change.
   wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
   when: trigger_reboot is changed
