---

 - name: disable swap
   lineinfile:
    path: /etc/fstab
    state: absent
    regexp: 'swap'
   register: fstab_contents

 - name: reboot if swap disabled
   reboot:
    reboot_timeout: 120
   when: fstab_contents.changed

 - name: configure apk
   lineinfile:
    path: /etc/apk/repositories
    line: 'http://mirror.leaseweb.com/alpine/edge/testing'

 - name: install packages
   apk: name=kubernetes,docker state=present

 - name: enable docker
   service:
    name: docker
    enabled: yes
    state: started

 - name: place kubelet init script
   template:
    src: kubelet
    dest: /etc/init.d/kubelet
    owner: root
    group: wheel
    mode: 0755

 - name: enable and start kubelet
   service:
    name: kubelet
    enabled: yes
    state: started
