---
 - name: configure apk
   lineinfile:
    path: /etc/apk/repositories
    line: 'http://mirror.leaseweb.com/alpine/edge/testing'

 - name: install packages
   apk: name=kubernetes state=present

 - name: create k8s user
   user:
     name: kubernetes

 - name: enforce kube /var/run
   file:
     path: /var/run/kubernetes
     state: directory
     mode: 0755
     owner: kubernetes
     group: kubernetes
