---
 - name: Install Common Packages
   pkgng: name=ca_root_nss,git state=present

 - name: Write motd
   template:
    src: motd
    dest: /etc/motd
    owner: root
    group: wheel
    mode: '0644'

# - name: Write sshd_config
#   template:
#    src: sshd_config
#    dest: /etc/ssh/sshd_config
#    owner: root
#    group: wheel
#    mode: '0644'
