---
 - name: Install common packages
   package: name=ca_root_nss,git,python36 state=present

 - name: Write motd
   template:
    src: motd
    dest: /etc/motd
    owner: root
    group: wheel
    mode: '0644'
