---
 - name: install nginx
   pkgng: name=nginx state=present 

 - name: Enable nginx
   service: name=nginx enabled=yes

 - name: Configuring NGINX
   template:
    src: nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: '0644'
   notify: restart nginx

 - name: checkout src script
   git:
    repo: 'https://github.com/nihr43/mirror.git'
    dest: /root/mirror

 - name: configure crontab
   lineinfile:
    path: /etc/crontab
    line: '0	0,12	*	*	*	root	/root/mirror/freebsd-src.sh'
