---
 - name: Install svn
   pkgng: name=subversion state=present

 - name: Write crontab
   template:
     src: crontab
     dest: /etc/crontab
     owner: root
     group: wheel
     mode: '0644'

 - name: Create /opt
   file:
     path: /opt
     state: directory
     owner: root
     group: wheel
     mode: '0755'

 - name: Copy src Update Script
   copy:
     src: src_update.sh
     dest: /opt/src_update.sh
     owner: root
     group: wheel
     mode: '0744'
     force: no

 - name: Copy Kernel Build Script
   copy:
     src: build_kernel.sh
     dest: /opt/build_kernel.sh
     owner: root
     group: wheel
     mode: '0744'
     force: no
