---
 - name: install minio
   pkgng: name=minio state=present

 - name: minio dir
   file:
    path: /opt/data
    state: directory
    owner: minio
    group: minio
    mode: 0660

 - name: enable minio
   service: name=minio enabled=yes

 - name: configure minio cluster
   lineinfile:
    path: /etc/rc.conf
    regexp: '^minio_disks='
    line: 'minio_disks="http://1d21-api:9000/opt/data http://7dd0-api:9000/opt/data http://3159-api:9000/opt/data http://d2a1-api:9000/opt/data"'
