---
 - name: install minio
   pkgng: name=minio,minio-client state=present

 - name: minio dir
   file:
    path: /var/db/minio
    state: directory
    owner: minio
    group: minio
    mode: 0770

 - name: minio config dir
   file:
    path: /usr/local/etc/minio
    state: directory
    owner: root
    group: wheel
    mode: 0644

 - name: enable minio
   service: name=minio enabled=yes

 - name: configure minio cluster
   lineinfile:
    path: /etc/rc.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
   with_items:
     - { regexp: '^minio_disks=', line: 'minio_disks="{{ minio_disks }}"' }
     - { regexp: '^minio_env=', line: 'minio_env="{{ minio_keys }}"' }
   notify: restart minio

 - name: ensure minio is running
   service: name=minio started=yes
