---
 - name: install minio
   pkgng: name=minio,minio-client state=present

 - name: minio dir
   file:
    path: /var/db/minio
    state: directory
    owner: minio
    group: minio
    mode: 0770

 - name: minio config dir
   file:
    path: /usr/local/etc/minio
    state: directory
    owner: root
    group: wheel
    mode: 0644

 - name: configure keys
   template: 
    src: config.json
    dest: /usr/local/etc/minio/config.json
    owner: minio
    group: minio
    mode: 0644
   notify: restart minio

 - name: enable minio
   service: name=minio enabled=yes

 - name: configure minio cluster
   lineinfile:
    path: /etc/rc.conf
    regexp: '^minio_disks='
    line: 'minio_disks="{{ minio_disks }}"'
   notify: restart minio

