---
 - name: configure apk
   lineinfile:
    path: /etc/apk/repositories
    line: 'http://mirror.leaseweb.com/alpine/edge/testing'

 - name: install packages
   apk: name=kubernetes state=present

 - name: create k8s user
   user:
     name: kubernetes

 - name: enforce kube /var/run
   file:
     path: /var/run/kubernetes
     state: directory
     mode: 0755
     owner: kubernetes
     group: kubernetes

 - name: place kube-apiserver init
   template:
    src: kube-apiserver
    dest: /etc/init.d/kube-apiserver
    owner: root
    group: wheel
    mode: 0755

 - name: place kube-scheduler init
   template:
    src: kube-scheduler
    dest: /etc/init.d/kube-scheduler
    owner: root
    group: wheel
    mode: 0755

 - name: place kube-controller-manager init
   template:
    src: kube-controller-manager
    dest: /etc/init.d/kube-controller-manager
    owner: root
    group: wheel
    mode: 0755
