---
 - name: configure apk
   lineinfile:
    path: /etc/apk/repositories
    line: 'http://mirror.leaseweb.com/alpine/edge/testing'

 - name: install packages
   apk: name=kubernetes state=present

 - name: place kube-apiserver init script
   template:
    src: kube-apiserver
    dest: /etc/init.d/kube-apiserver
    owner: root
    group: wheel
    mode: 0755
