---
 - name: install elasticsearch
   pkgng: name=elasticsearch6 state=present

 - name: enable elasticsearch
   service: name=elasticsearch enabled=yes

 - name: configure elasticsearch
   template:
    src: elasticsearch.yml
    dest: /usr/local/etc/elasticsearch/elasticsearch.yml
    owner: root
    group: wheel
    mode: 0755
   notify: restart elasticsearch
