---
 - name: install packages
   apk: name=rethinkdb state=present

 - name: place rethink conf
   template:
    src: default.conf
    dest: /etc/rethinkdb/default.conf
    owner: root
    group: wheel
    mode: 0644
   notify: restart rethinkdb

 - name: enable rethinkdb
   service:
    name: rethinkdb
    enabled: yes
    state: started
