---
 - name: install packages
   apk: name=rethinkdb state=present

 - name: place rethink conf
   template:
    src: default.conf
    dest: /etc/rethinkdb/instances.d/default.conf
    owner: root
    group: wheel
    mode: 0644
   notify: restart rethinkdb

 - name: place rethink init
   template:
    src: rethinkdb
    dest: /etc/init.d/rethinkdb
    owner: root
    group: wheel
    mode: 0755

 - name: enable rethinkdb
   service:
    name: rethinkdb
    enabled: yes
    state: started
