---

 - name: copy generic kernel for freebsd-update
   copy:
    src: GENERIC
    dest: /boot/GENERIC

 - name: freebsd-update fetch
   raw: env PAGER=cat freebsd-update fetch

 - name: freebsd-update install
   raw: env PAGER=cat freebsd-update install
   ignore_errors: true

 - name: copy kernel to hosts
   copy:
    src: kernel
    dest: /boot/kernel/kernel
    force: yes

 - name: reboot
   shell: shutdown -r +1sec
   ignore_errors: true
