---
 - name: figure my location
   shell: "hostname | awk -F '-r' '{print $NF}'"
   register: rack_num

 - debug: msg="rack_num is {{ rack_num.stdout }}"

 - name: configure static address
   lineinfile: dest=/etc/rc.conf insertafter=EOF line='ifconfig_vtnet1="172.16.{{ rack_num.stdout }}.2/24 up"'

 - name: configure default route
   lineinfile: dest=/etc/rc.conf insertafter=EOF line='dafaultrouter="172.16.{{ rack_num.stdout }}.1"'

 - name: configure dns
   lineinfile: dest=/etc/resolv.conf insertafter=EOF line='nameserver 8.8.8.8'

 - name: install isc-dhcp43-server
   pkgng: name=isc-dhcp43-server state=present

 - name: enable isc-dhcp43-server
   service: name=isc-dhcpd enabled=yes
   notify: start isc-dhcpd

 - name: configure isc-dhcp43-server
   template: 
    src: dhcpd.conf.j2
    dest: /usr/local/etc/dhcpd.conf
    owner: root
    group: wheel
    mode: 0644
   notify: restart isc-dhcpd

 - name: set dhcp server interface
   lineinfile: dest=/etc/rc.conf insertafter=EOF line='dhcpd_ifaces="vtnet1"'
   notify: restart isc-dhcpd
