---
 - name: figure my location
   shell: hostname | awk -F '-r' '{print $NF}'
   register: rack_num

 - name: figure my services address
   shell: echo -n "172.16.{{ rack_num }}.2"
   register: services_address

 - name: figure address of my gateway
   shell: echo -n "172.16.{{ rack_num }}.1"
   register: gateway_address

 - name: install isc-dhcp43-server
   pkgng: name=isc-dhcp43-server state=present

 - name: enable isc-dhcp43-server
   service: name=isc-dhcpd enabled=yes
   notify: start isc-dhcpd

 - name: configure isc-dhcp43-server
   template: 
    src: dhcpd.conf.j2
    dest: /usr/local/etc/dhcpd.conf
    owner: root
    group: wheel
    mode: 0644
   notify: restart isc-dhcpd

 - name: set dhcp server interface
   lineinfile: dest=/etc/rc.conf insertafter=EOF line='dhcpd_ifaces="vtnet1"'
   notify: restart isc-dhcpd
